### ISSUE TITLE
Debian buster broken CI configuration

### ISSUE THREAD

**Issue by Senen** [consuldemocracy/installer#222]
## References

Something happened out there, as the tests for Debian Buster were suddenly broken (without introducing changes).

It seems something changed in the Debian image or the CI's GitHub Actions workflows, as the installer works fine when running manually against the latest Debian Buster Vagrant image available. So, the CI configuration for Debian Buster tests seems to be the issue.

# Other interesting information
Debian Buster images have python 2 and python 3 installed by default.

```
vagrant@buster:~$ python --version
Python 2.7.16
vagrant@buster:~$ python3 --version
Python 3.7.3
```

Debian Bullseye images just has python 3 installed by default.

```
vagrant@bullseye:~$ python --version
-bash: python: command not found
vagrant@bullseye:~$ python2 --version
-bash: python2: command not found
vagrant@bullseye:~$ python3 --version
Python 3.9.2
```

**Debian Buster EOL**
<img width="647" alt="Captura de pantalla 2023-09-21 a las 17 38 23" src="https://github.com/consuldemocracy/installer/assets/15726/8aac1002-aadd-41a2-bdd5-338a376507ea">

## Error

The error we are getting in the CI when running the installer in Debian buster is the following:

```
Run ansible-playbook consul.yml -i hosts --extra-vars "env=staging domain=localhost errbit=False"
  ansible-playbook consul.yml -i hosts --extra-vars "env=staging domain=localhost errbit=False"
  shell: sh -e {0}
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 63, in <module>
    import ansible.constants as C
  File "/usr/local/lib/python3.7/dist-packages/ansible/constants.py", line 15, in <module>
    from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
  File "/usr/local/lib/python3.7/dist-packages/ansible/config/manager.py", line 17, in <module>
    from yaml import load as yaml_load
ModuleNotFoundError: No module named 'yaml'
Error: Process completed with exit code 1.
```
As the error says that the `No module named 'yaml'`, I searched how we install Ansible and its dependencies and found a small difference between the output of the CI task to install Ansible in a successful build versus a failed build. 👇🏼 

**Log from task  "pip3 install ansible" in a successful CI run**

```
Run pip3 install ansible
  pip3 install ansible
  shell: sh -e {0}
The directory '/github/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/github/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/fd/f8/071905c6a67592d0852a9f340f6ab9226861eeeb97fdf4068642b22edcf3/ansible-4.10.0.tar.gz (36.8MB)
Collecting ansible-core~=2.11.7 (from ansible)
  Downloading https://files.pythonhosted.org/packages/98/ea/2935bf0864196cd2c9d14548e399a110f48b3540664ddc462b39ff0b822d/ansible-core-2.11.12.tar.gz (7.1MB)
Collecting PyYAML (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/eb/5f/6e6fe6904e1a9c67bc2ca5629a69e7a5a0b17f079da838bab98a1e548b25/PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596kB)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-core~=2.11.7->ansible) (2.6.1)
Collecting jinja2 (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (133kB)
Collecting packaging (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (48kB)
Collecting resolvelib<0.6.0,>=0.5.3 (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/6b/f5/1b4375dbe7e3dddf074d206054ab3e27de0fdb2d32e64a1d5da25f813927/resolvelib-0.5.5-py2.py3-none-any.whl
Collecting MarkupSafe>=2.0 (from jinja2->ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/6d/7c/59a3248f411813f8ccba92a55feaac4bf360d29e2ff05ee7d8e1ef2d7dbf/MarkupSafe-2.1.3.tar.gz
Installing collected packages: PyYAML, MarkupSafe, jinja2, packaging, resolvelib, ansible-core, ansible
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for ansible-core: started
    Running setup.py install for ansible-core: finished with status 'done'
  Running setup.py install for ansible: started
    Running setup.py install for ansible: still running...
    Running setup.py install for ansible: finished with status 'done'
Successfully installed MarkupSafe-2.1.3 PyYAML-6.0 ansible-4.10.0 ansible-core-2.11.12 jinja2-3.1.2 packaging-23.1 resolvelib-0.5.5
```

**Log from task  "pip3 install ansible" in a failed CI run**

```
Run pip3 install ansible
  pip3 install ansible
  shell: sh -e {0}
The directory '/github/home/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/github/home/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/fd/f8/071905c6a67592d0852a9f340f6ab9226861eeeb97fdf4068642b22edcf3/ansible-4.10.0.tar.gz (36.8MB)
Collecting ansible-core~=2.11.7 (from ansible)
  Downloading https://files.pythonhosted.org/packages/98/ea/2935bf0864196cd2c9d14548e399a110f48b3540664ddc462b39ff0b822d/ansible-core-2.11.12.tar.gz (7.1MB)
Collecting PyYAML (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz (125kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible-core~=2.11.7->ansible) (2.6.1)
Collecting jinja2 (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (133kB)
Collecting packaging (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (48kB)
Collecting resolvelib<0.6.0,>=0.5.3 (from ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/6b/f5/1b4375dbe7e3dddf074d206054ab3e27de0fdb2d32e64a1d5da25f813927/resolvelib-0.5.5-py2.py3-none-any.whl
Collecting MarkupSafe>=2.0 (from jinja2->ansible-core~=2.11.7->ansible)
  Downloading https://files.pythonhosted.org/packages/6d/7c/59a3248f411813f8ccba92a55feaac4bf360d29e2ff05ee7d8e1ef2d7dbf/MarkupSafe-2.1.3.tar.gz
Installing collected packages: PyYAML, MarkupSafe, jinja2, packaging, resolvelib, ansible-core, ansible
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for ansible-core: started
    Running setup.py install for ansible-core: finished with status 'done'
  Running setup.py install for ansible: started
    Running setup.py install for ansible: finished with status 'done'
Successfully installed MarkupSafe-2.1.3 PyYAML ansible-4.10.0 ansible-core-2.11.12 jinja2-3.1.2 packaging-23.1 resolvelib-0.5.5
```

There is a small difference in lines referencing `PyYAML` libraries. It may be the cause 🤔.

**Comment by Senen** [comment]
Considering that the Debian Buster won't receive security updates anymore, maybe our best option is to drop support for it from the installer and maybe add support for Debian Bookwork, so we encourage new Consul Democracy installations using Debian versions with security upgrades.

**Comment by Senen** [comment]
The first way I tried to reproduce the error was creating a VM with the latest Bebian Buster image available and try to run the same steps the `debian.yml` workflow uses with no luck. The process succeeds with no track of the error we are getting when running on the CI.

Now, I'm trying to reproduce the error using [nektos/act](https://github.com/nektos/act) to run the Debian Buster tests locally.
